## Numpy

In [ ]:
import numpy as np

In [ ]:
a = 20
b = np.array(20) # scalar
print(type(a), type(b))

<class 'int'> <class 'numpy.ndarray'>


In [ ]:
x = np.array([1, 1.2, 1.5, 1.8, 2]) #vector
x

array([1. , 1.2, 1.5, 1.8, 2. ])

In [ ]:
# Độ dài
print("length of vector: ", x.shape) # or len(x)

# Định dạng của véc tơ
print("vector type: ", x.dtype)

# Tổng của các phần tử 
print("sum of vector: ", x.sum())

# Trung bình các phần tử
print("mean of vector: ", x.mean())

# Giá trị nhỏ nhất
print("min of vector: ", x.min())

# Giá trị lớn nhất
print("max of vector: ", x.max())

length of vector:  (5,)
vector type:  float64
sum of vector:  7.5
mean of vector:  1.5
min of vector:  1.0
max of vector:  2.0


In [ ]:
x = np.array([1, 2, 1.5, 1.8, 1.9])
y = np.array([1.1, 2.2, 1.2, 1.6, 1.7])
print("x + y: ", x + y)
print("x - y: ", x - y)
print("x * y: ", x * y)

x + y:  [2.1 4.2 2.7 3.4 3.6]
x - y:  [-0.1 -0.2  0.3  0.2  0.2]
x * y:  [1.1  4.4  1.8  2.88 3.23]


In [ ]:
A = np.array([[1, 2, 3], 
              [3, 2, 1]])

# shape của matrix A
print(A.shape)

# Chuyen vi
A.T

(2, 3)


array([[1, 3],
       [2, 2],
       [3, 1]])

In [ ]:
# element wise
A = np.array([[1, 2, 3], 
              [3, 2, 1]])

B = np.array([[2, 1, 2], 
             [1, 3, 0]])

print(A*B)

print(B.shape)
B = B.reshape(3, 2)
print(A@B)

[[2 2 6]
 [3 6 0]]
(2, 3)
[[15  3]
 [13  5]]


In [ ]:
b = np.array([[1, 2, 3]])
print(b.shape)
print(b.T.shape)

#vector -> khong co chieu thu 2
c = np.array([1, 2, 3])
print(c.shape)
print(c.T.shape)

(1, 3)
(3, 1)
(3,)
(3,)


In [ ]:
# broadcasting
a = np.array([1, 2, 3])        # Shape (3,)
b = 2                          # Scalar, shape ()
c = a + b                      # Broadcasting
print(c)  # [3 4 5] -> b = [2 2 2]

d = np.array([[1, 2, 3],
              [4, 5, 6]])       # Shape (2, 3)
e = np.array([10, 20, 30])      # Shape (3,)

f = d + e                       # Broadcasting theo chiều hàng (row)
print(f) # e = [10, 20, 30]
        #       [10, 20, 30]

[3 4 5]
[[11 22 33]
 [14 25 36]]


In [ ]:
# ma tran nghich dao
A = np.array([[1, 2, 3], 
              [3, 2, 1],
              [4, 2, 2]])

A_inv = np.linalg.pinv(A)
print(A_inv)

[[-0.25 -0.25  0.5 ]
 [ 0.25  1.25 -1.  ]
 [ 0.25 -0.75  0.5 ]]


In [ ]:
# slicing
A = np.array([[1, 2, 3], 
              [3, 2, 1],
              [4, 2, 2]])

# Truy cập ma trận con từ 2 dòng đầu tiên và 2 cột đầu tiên.
print(A[:2, :2])

print(A[:2, :])

print(A[:2, ::-1])

print(A[2, -2:]) #print(A[2:3, -2:][0])

print(A[::2, :])

# Truy cập một index cụ thể , ví dụ dòng 0, 2 của ma trận
print(A[[0, 2], :])

[[1 2]
 [3 2]]
[[1 2 3]
 [3 2 1]]
[[3 2 1]
 [1 2 3]]
[2 2]
[[1 2 3]
 [4 2 2]]
[[1 2 3]
 [4 2 2]]


In [ ]:
# ma trận nhân vector
X = np.array([[100, 120, 80, 90, 105, 95], 
              [2, 3, 2, 2, 3, 2]])
w = np.array([[10], [100]])
y = X.T@w
print(y)

[[1200]
 [1500]
 [1000]
 [1100]
 [1350]
 [1150]]


In [ ]:
# Chuẩn 2 L2
x = np.random.randn(10)
np.linalg.norm(x, ord=2)

np.float64(1.887556109812624)

In [ ]:
# Chuẩn 1 L1
print(np.linalg.norm(x, ord=1))
# hoặc 
np.abs(x).sum()

4.6272496924913415


np.float64(4.6272496924913415)

In [ ]:
# Định thức
A = np.array([[1, 2],
              [3, 4]])

# Định thức của ma trận
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [ ]:
# Khởi tạo các vector x, y ngẫu nhiên có độ dài 100
x = np.random.randn(100)
y = np.random.randn(100)

# Ma trận hiệp phương sai
np.cov(x, y)

array([[ 0.89662038, -0.058922  ],
       [-0.058922  ,  1.24163668]])

In [ ]:
# Phương sai của x
np.var(x, ddof=1)

# Hoặc 
x.var(ddof=1)

np.float64(0.8966203798210587)

![](attachment:image.png)

In [ ]:
import numpy as np

np.array([1, 2, 3]) + np.array([[4, 5, 6]])

array([[5, 7, 9]])

In [ ]:
np.array([[5, 7, 9]]).shape

(1, 3)

In [ ]:
np.array([-1, -2, -3]).shape

(3,)

## Tensor

scalar : dim=0, shape=()

In [ ]:
x = np.array(12)
print(x)
print('x.ndim =', x.ndim)
print('x.shape =', x.shape)

12
x.ndim = 0
x.shape = ()


vector : (dt, so phong, gia) = (2000, 2, 500)

In [ ]:
x = np.array([12, 3, 6, 14])
print(x)
print('x.ndim =', x.ndim)
print('x.shape =', x.shape)

[12  3  6 14]
x.ndim = 1
x.shape = (4,)


matrix: set(same dim vectors)

In [ ]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 1, 2, 3]]
)
print(x)
print('x.ndim =', x.ndim)
print('x.shape =', x.shape)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
x.ndim = 2
x.shape = (3, 4)


3d tensor: set(same dim matrix)

In [ ]:
x = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]],
    [[13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24]]
])
print('x.ndim =', x.ndim)
print('x.shape =', x.shape)

x.ndim = 3
x.shape = (4, 2, 3)
