## import lib

In [1]:
import numpy as np

Numpy : array -> speed => large dataset

numpy array all items must be the same data type -> change 1 item that has more complex data type -> all items change to that data type

## Tạo mảng và ma trận

In [2]:
# 1 chiều
a1 = np.array([1, 2, 3, 4, 5])
print(a1.shape)
a1

(5,)


array([1, 2, 3, 4, 5])

In [6]:
# nhiều chiều
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2.shape)
a2

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3 = np.array([[1], [2], [3]])
print(a3.shape)
a3

(3, 1)


array([[1],
       [2],
       [3]])

In [ ]:
# tạo mảng tự động -> giống list comprehension
#np.arange(start, stop, step)
np.arange(0, 5, 2) 

array([0, 2, 4])

In [2]:
# chia đều khoảng từ start tới end
# np.linspace(start, end, khoảng chia)

np.linspace(0, 1, 5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.zeros(4, dtype=float) # 1D array

array([0., 0., 0., 0.])

In [ ]:
np.ones((2, 3), dtype=int) # 2x3 matrix

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# np.eye(N, M=None, k=0, dtype=float) M, N: hàng, cột; k = vị trí đường chéo
np.eye(2, 3, dtype=int) # bậc thang

array([[1, 0, 0],
       [0, 1, 0]])

In [3]:
np.eye(3, dtype=int) # vuông

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# ma trận đơn vị vuông (chuẩn không đổi được)
np.identity(4, dtype=int) 

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# ma trận 2x3 toàn số 8
np.full((2, 3), 8, dtype=int) 

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
# demo matrix
matrix_demo = np.arange(20).reshape(5, 4)
print(matrix_demo)
print(matrix_demo.T) # chuyển vị

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [ ]:
np.random.seed(13) # đảm bảo các lần sinh ra giá trị đều giống nhau
np.random.rand(3) # sinh ra các giá trị khác nhau

array([0.77770241, 0.23754122, 0.82427853])

In [7]:
# mỗi giá trị là 1 con đường riêng biệt 
# cùng đường -> cùng kết quả, khác đường -> khác kq
np.random.seed(0) 

samples = np.random.choice([1, 2, 3], size=5, p=[0.2, 0.3, 0.5]) 
samples

array([3, 3, 3, 3, 2])

In [ ]:
np.random.randint(30, 50, 8) #(start, end, number of element)

array([44, 41, 46, 43, 42, 38, 36, 32], dtype=int32)

In [ ]:
np.random.randint(0, 10, size=(2, 4)) #(start, end, type of matrix)

array([[6, 3, 8, 7],
       [5, 4, 0, 2]], dtype=int32)

## Xử lý mảng và ma trận

In [19]:
a1 = np.array([[1,2,3], [4,5,6]])
a1.shape

(2, 3)

In [ ]:
a2 = a1.reshape(3, 2)
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a1.size # số phần tử của ma trận

6

In [ ]:
a2 = a2.flatten() # copy mảng
a2

array([1, 2, 3, 4, 5, 6])

In [20]:
# np.where(condition, x, y) -> giống if else
a1 = np.where(a1<3, a1, a1+2) # condition, array, another array
a1

array([[1, 2, 5],
       [6, 7, 8]])

In [ ]:
a2 = np.where(a2<4, a2, a2+4) # cùng shape mới được
a2

array([[ 1,  2,  3],
       [12, 13, 14],
       [15, 16, 17]])

In [11]:
# slicing -> mảng có cùng địa chỉ với mảng đầu -> change thì mảng kia cũng change
# mảng 1 chiều
a2[::-1]

array([[15, 16, 17],
       [12, 13, 14],
       [ 1,  2,  3]])

In [16]:
a2[len(a2)-1:len(a2)] 

array([[15, 16, 17]])

In [ ]:
a2[len(a2)-1:len(a2), ::-1] 

array([[17, 16, 15]])

In [22]:
# mảng nhiều chiều
a1[0:2, 0:2] # [hàng (x, y-1) , cột (x, y-1)]

array([[1, 2],
       [6, 7]])

In [24]:
a3 = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

# Cách 1: số chiều giảm 
row_r1 = a3[1, :]
print(row_r1, row_r1.shape)

[5 6 7] (3,)


In [25]:
# Cách 2: số chiều được giữ nguyên 
row_r2 = a3[1:2, :]
print(row_r2, row_r2.shape)

[[5 6 7]] (1, 3)


In [27]:
# Cách 1: số chiều giảm 
col_r1 = a3[:, 1]
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [28]:
# Cách 2: số chiều được giữ nguyên 
col_r2 = a3[:, 1:2]
print(col_r2, col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [29]:
#chọn các phần tử của ma trận theo điều kiện thành 1 array
a1[(a1 > 3) & (a1 <= 7)] 

array([5, 6, 7])

In [ ]:
# boolean array -> tạo thành ma trận true false vs các giá trị phụ thuộc điều kiện
bool_arr = (a1 > 4)
bool_arr

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
# nên dùng flatten() trước
# np.put(arr, indices, values) đổi values tại indexes
np.put(a1, [1, 2, 5], [2, 2, 2])
a1

array([[1, 2, 2],
       [6, 7, 2]])

In [ ]:
np.unique(a1)

array([1, 2, 6, 7])

In [ ]:
# ma trận chuyển vị
a1.transpose()
a1.T
a1.swapaxes(0, 1) # 0:hàng, 1:cột

array([[1, 6],
       [2, 7],
       [2, 2]])

In [31]:
arr1 = np.random.randint(10, size=(2, 3))
arr2 = np.random.randint(20, size=(2, 3))

# stacking
horizontal = np.hstack((arr1, arr2)) #np.column_stack
print(horizontal)

vertical = np.vstack((arr1, arr2)) #np.row_stack
print(vertical)

[[ 5  2  4 12  1  6]
 [ 7  6  8  7 14 17]]
[[ 5  2  4]
 [ 7  6  8]
 [12  1  6]
 [ 7 14 17]]


In [ ]:
# spliting
np.hsplit(horizontal, 3) # 3 phần đều nhau

[array([[5, 2],
        [7, 6]]),
 array([[ 4, 12],
        [ 8,  7]]),
 array([[ 1,  6],
        [14, 17]])]

In [ ]:
np.hsplit(horizontal, [1, 4]) # trước index 1 và trước index 4

[array([[5],
        [7]]),
 array([[ 2,  4, 12],
        [ 6,  8,  7]]),
 array([[ 1,  6],
        [14, 17]])]

In [ ]:
# chia 3 phần từ cột 2 đến 6
np.hsplit(horizontal, (2, 6)) # np.hsplit(horizontal, [2, 6]) -> kết quả giống nhau

[array([[5, 2],
        [7, 6]], dtype=int32),
 array([[ 4, 12,  1,  6],
        [ 8,  7, 14, 17]], dtype=int32),
 array([], shape=(2, 0), dtype=int32)]

In [34]:
new_ar1 = np.concatenate(([1, 2, 3, 5], [7, 8, 9, 10]), axis=0) # axis=0: vertical, axis=1: horizontal
new_ar2 = np.concatenate(([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]), axis=1)   
print(new_ar1)
print(new_ar2)

[ 1  2  3  5  7  8  9 10]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [38]:
split_ar1 = np.split(new_ar1, 2) # chia làm 2 phần bằng nhau
split_ar2 = np.array_split(new_ar1, 3) # chia làm 3 phần ko đều nhau phần đầu sẽ lệch
print(split_ar1)
print(split_ar2)

[array([1, 2, 3, 5]), array([ 7,  8,  9, 10])]
[array([1, 2, 3]), array([5, 7, 8]), array([ 9, 10])]


In [39]:
new_dstack = np.dstack(([1, 2, 3], [1, 2, 3])) # depth stacking
print(new_dstack)
print(new_dstack.shape)

[[[1 1]
  [2 2]
  [3 3]]]
(1, 3, 2)


### Phép toán

In [ ]:
print(arr1)
print(arr2)

[[5 2 4]
 [7 6 8]]
[[12  1  6]
 [ 7 14 17]]


In [ ]:
# phép tính với mảng
print(arr1 + arr2)
print(np.add(arr1, arr2))
print(np.remainder(arr1, arr2)) # chia lấy dư

# np.subtract(x, y) (x-y), np.divide(x, y) (x/y) , np.multiply(x, y) (x * y), np.mod(x, y) (x%y )
np.sqrt(arr2) #căn bậc 2 cho từng phần tử

[[17  3 10]
 [14 20 25]]
[[17  3 10]
 [14 20 25]]
[[5 0 4]
 [0 6 8]]


array([[3.46410162, 1.        , 2.44948974],
       [2.64575131, 3.74165739, 4.12310563]])

In [ ]:
arr2 = arr2.reshape(3, 2)
print(arr2.shape)

print(np.matmul(arr1, arr2)) # chỉ dùng cho nhân ma trận
print(arr1.dot(arr2)) # tích vô hướng, nhân ma trận, vector-matrix,...
print(np.dot(arr1, arr2)) #giống mtx.dot()

[[128  87]
 [232 185]]
[[128  87]
 [232 185]]
[[128  87]
 [232 185]]


In [ ]:
print(a1)
# tính tổng
print(np.sum(a1))  
# Tính tổng theo từng cột 
print(np.sum(a1, axis=0))  
# Tính tổng theo từng hàng
print(np.sum(a1, axis=1)) 
# max-min -> value

print(a1.max(axis=1), a1.min(axis=0))
# argmax-argmin -> index
print(np.argmax(a1, axis=1), np.argmin(a1, axis=0))
# inner product
print(np.inner(a1, a3))
#absolute
np.absolute([-2, 0, -5, 90])

[[1 2 2]
 [6 7 2]]
20
[7 9 4]
[ 5 15]
[2 7] [1 2 2]
[1 1] [0 0 0]
[[ 11  31  51]
 [ 26  86 146]]


array([ 2,  0,  5, 90])

In [ ]:
print(a1)
# e^x[i]
print(np.exp(a1))
#log(x[i])
print(np.log(a1))
#pi
print(np.pi)
#sin()
print(np.sin(np.pi/2))
# tanh
print(np.tanh(np.array([-1, 0, 1])))
#rad2deg -> np.sin(), np.cos(), np.arcsin(),...
print(np.rad2deg(np.pi))
# tim goc
x = np.arcsin(np.array([1, -1, 0.1]))
print(x)

x = np.gcd.reduce(np.array([20, 8, 32, 36, 16])) #np.lcm -> 2 so , np.lcm.reduce() -> array
print(x)

[1 2 3 4 5]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
3.141592653589793
1.0
[-0.76159416  0.          0.76159416]
180.0
[ 1.57079633 -1.57079633  0.10016742]
4


In [ ]:
# lam tron
#Loại bỏ các số thập phân và trả về số thực gần nhất với số 0. 
arr = np.trunc([-3.1666, 3.6667])
print(arr)
arr = np.fix([-3.1666, 3.6667])
print(arr)

arr = np.around(3.1666, 2) # làm tròn n chữ số thập phan
print(arr)
arr = np.floor([-3.1666, 3.6667])
print(arr)
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [ ]:
ar1 = [1, 2, 3, 5]
ar2 = [3, 5, 10, 2]
print(np.union1d(ar1, ar2))
print(np.intersect1d(ar1, ar2))
print(np.setdiff1d(ar1, ar2))
print(np.setxor1d(ar1, ar2))

[ 1  2  3  5 10]
[2 3 5]
[1]
[ 1 10]


### Thống kê

In [ ]:
a5 = np.arange(10, dtype=int)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(np.mean(a5)) # không có trọng số
print(np.median(a5))
print(np.average(a5, weights=np.arange(10, dtype=int))) # có trọng số
print(np.std(a5))
print(np.var(a5))
print(np.percentile(a5, 50, axis=0))

4.5
4.5
6.333333333333333
2.8722813232690143
8.25
4.5


### Thư viện linalg

In [43]:
from numpy import linalg as LA

ar1 = np.random.randint(1, 5, (2, 2))
ar2= np.random.randint(6, 10, (2, 2))
ar3 = np.random.randint(10, 20, (2, 2))

print(ar1, ar2, ar3, sep=';')

[[1 1]
 [2 2]];[[8 6]
 [6 7]];[[14 19]
 [18 11]]


In [ ]:
LA.multi_dot([ar1, ar2, ar3]) # dot product nhưng tối ưu

array([[430, 409],
       [860, 818]], dtype=int32)

In [ ]:
print(LA.norm(ar1))
print(LA.eig(ar1))
print(LA.eigvals(ar1))
print(LA.cond(ar2))
print(LA.inv(ar2))
print(LA.det(ar2))
print(LA.matrix_power(ar1, 2))

3.1622776601683795
EigResult(eigenvalues=array([0., 3.]), eigenvectors=array([[-0.70710678, -0.4472136 ],
       [ 0.70710678, -0.89442719]]))
[0. 3.]
9.140597967047107
[[ 0.35 -0.3 ]
 [-0.3   0.4 ]]
19.999999999999996
[[3 3]
 [6 6]]


### Broadcasting

Broadcasting cho phép thực thi các phép toán trên các mảng có kích thước khác nhau.

Ví dụ: chúng ta muốn cộng vector cho mỗi hàng của ma trận. Chúng ta có thể làm như sau:

In [ ]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
Y = np.empty_like(X)

# Cách 1: Thêm vector v vào mỗi hàng của ma trận X bằng vòng lặp 
for i in range(4):
    Y[i, :] = X[i, :] + v
    
print('Matrix X: \n', X)
print('\nVector v: \n', v)
print('\nMatrix Y: \n', Y)

Matrix X: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector v: 
 [1 0 1]

Matrix Y: 
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Cách này hoạt động bình thường với ma trận X nhỏ. Khi ma trận X lớn, việc sử dụng vòng lặp này sẽ rất chậm.

Chúng ta có thể thực hiện mục đích trên bằng cách xếp chồng nhiều bản sao của v theo chiều dọc, sau đó thực hiện phép tính tổng với X. Chúng ta có thể thực hiện phương pháp này như sau:


In [ ]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

# Xếp chồng 4 bản sao của v lên nhau:
V_t = np.tile(v, (4, 1))

# Thực hiện phép cộng
Y = X + V_t

print('Matrix X: \n', X)
print('\nVector v: \n', v)
print('\nMatrix v: \n', V_t)
print('\nMatrix Y: \n', Y)

Matrix X: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector v: 
 [1 0 1]

Matrix v: 
 [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

Matrix Y: 
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting cho phép chúng ta thực thi tính toán này mà không cần phải làm thêm các bước thêm nào.
import numpy as np

In [ ]:
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
Y = X + v 
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
